name: Generate Snake Animation

on:
 schedule:
    - cron: '0 */12 * * *' # Execute every 12 hours
 workflow_dispatch: # Manual trigger
 push:
    branches:
      - master # Trigger on push to master branch

jobs:
 generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sujansince2003 # Your GitHub username
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # The branch to push the SVG to
          build_dir: dist # Directory containing the SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication
